// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var HelloWorldReact$FunWithReasonReact = require("./HelloWorldReact.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, HelloWorldReact$FunWithReasonReact.make(/* array */[])), "index");

/*  Not a pure module */
